services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    env_file:
      - .env
    ports:
      - 9000:9000
    depends_on:
      db:
        condition: service_healthy
    container_name: profiles-server
  db:
    image: postgres
    restart: always
    user: ${POSTGRES_USER}
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: profiles-db
  migration:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - server
    env_file:
      - .env
    command: sh -c "npx knex migrate:latest --knexfile=./knexfile.js"
    volumes:
      - ./knexfile.js:/home/node/app/knexfile.js
      - ./db:/home/node/app/db
    container_name: profiles-migration
volumes:
  db-data:
