name: Build

on:
  push:
    branches:
      - masmainter
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: latest
      
      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build